package modele.item;

public enum ItemType {
	
	PERSONNAGE,
	MAP, 
	LIEU,
	POI,
	MISSION,
	ACTION_COMBAT,
	MUSIQUE,
	FILM,

	// Consommables
	POTION_VIE_25,
	POTION_VIE_50,
	POTION_VIE_75,
	POTION_VIE_100,
	POTION_MANA_25,
	POTION_MANA_50,
	POTION_MANA_75,
	POTION_MANA_100,
	
	POTION_COMBAT,
	
	BONUS_STAT_CHANCE_5,
	BONUS_STAT_CHANCE_10,
	BONUS_STAT_CHANCE_20,
	BONUS_STAT_EXPLOIT_5,
	BONUS_STAT_EXPLOIT_10,
	BONUS_STAT_EXPLOIT_20,
	BONUS_STAT_TECHNIQUE_5,
	BONUS_STAT_TECHNIQUE_10,
	BONUS_STAT_TECHNIQUE_20,
	BONUS_STAT_ENDURANCE_5,
	BONUS_STAT_ENDURANCE_10,
	BONUS_STAT_ENDURANCE_20,
	BONUS_STAT_RAPIDITE_5,
	BONUS_STAT_RAPIDITE_10,
	BONUS_STAT_RAPIDITE_20,
	BONUS_STAT_RESISTANCE_5,
	BONUS_STAT_RESISTANCE_10,
	BONUS_STAT_RESISTANCE_20,
	BONUS_STAT_AGILITE_5,
	BONUS_STAT_AGILITE_10,
	BONUS_STAT_AGILITE_20,
	BONUS_STAT_INTELLIGENCE_5,
	BONUS_STAT_INTELLIGENCE_10,
	BONUS_STAT_INTELLIGENCE_20,
	BONUS_STAT_NERVOSITE_5,
	BONUS_STAT_NERVOSITE_10,
	BONUS_STAT_NERVOSITE_20,
	BONUS,
	
	// Objets Quete
	OBJET_QUETE,
	
	// Equipements
	TETE,
	LUNETTES,
	TORSE,
	BRAS,
	MAINS,
	DOIGT,
	CEINTURE,
	JAMBES,
	PIEDS,
	
	ARME,
	DROGUE,
	
	// Collections
	BILLE,	
	POG,
	CARTE_FOOT,
	CARTE_DBZ,
	CARTE_CRADOS,
	CARTE_STARWARS,
	CARTE_MAGIC;
	
}
