package modele.evenement;

public enum EvenementTheme {
	ANNIVERSAIRE,
	ARRIVEE_NOUVEAU_PERSONNAGE,
	VACANCE,
	SORTIE_MUSIQUE,
	SORTIE_JEU_SOCIETE,
	SORTIE_JEU_VIDEO,
	SORTIE_FILM,
	SORTIE_SERIE,
	SORTIE_EMISSION,
	SORTIE_DESSIN_ANIME,
	SORTIE_PUB,
	SORTIE_OBJET,
	HISTOIRE;
	
}
