package modele.item.personnage.action;

public enum SortType {
	DEGATS_MONO, 
	DEGATS_MULTI, 
	DEGATS_ALL,
	BOUCLIER_MONO, 
	BOUCLIER_MULTI, 
	AURA_MONO, 
	AURA_MULTI, 
	REGEN_VIE_MONO, 
	REGEN_VIE_MULTI, 
	REGEN_MANA_MONO, 
	REGEN_MANA_MULTI, 
	RESURRECTION_MONO, 
	RESURRECTION_MULTI; 
}
